# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouyinDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Just'
  pod 'Kingfisher'
  pod 'MarqueeLabel'
  pod 'NVActivityIndicatorView'
  pod 'SnapKit'
  pod 'ChainableAnimations'



  # Pods for DouyinDemo

end 
