# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '002-shell打包上线' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  # Pods for 002-shell打包上线
  target '002-shell打包上线Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '002-shell打包上线UITests' do
    # Pods for testing
  end

end
